const overlay=document.getElementById('overlay'),modal=document.getElementById('modal');
function openModal(html){modal.innerHTML=html;overlay.classList.remove('hidden')}
function closeOverlay(e){if(e.target===overlay)overlay.classList.add('hidden')}
function showAdd(){openModal(`<h2>Add Account</h2><div class="tabs"><button class="selected">Scan QR Code</button><button>Enter Setup Key</button></div><div class="qr">▦</div><p style="text-align:center">Scan the QR code provided by your account.</p><button class="primary" onclick="showManual()">Enter Setup Key Instead</button>`)}
function showManual(){openModal(`<h2>Add Account</h2><div class="tabs"><button>Scan QR Code</button><button class="selected">Enter Setup Key</button></div><div class="field"><label>ACCOUNT NAME</label><input placeholder="e.g. Google"></div><div class="field"><label>EMAIL / USERNAME</label><input placeholder="you@example.com"></div><div class="field"><label>SECRET KEY</label><input placeholder="Enter setup key"></div><div class="field"><label>TYPE</label><select><option>Time based (TOTP)</option></select></div><button class="primary" onclick="alert('Demo account saved')">Save Account</button>`)}
function openAccount(name,email,code){openModal(`<h2>${name}</h2><p>${email}</p><div style="text-align:center;padding:24px 0"><div style="font-size:42px;font-weight:800;color:#6735df;letter-spacing:3px">${code}</div><p>Code expires in <b>18s</b></p></div><div class="settings-row"><span>Type<small>TOTP</small></span><b>30 sec</b></div><div class="settings-row"><span>Algorithm<small>SHA-1</small></span><b>6 digits</b></div>`)}
function showSettings(){openModal(`<h2>Settings</h2><div class="settings-row"><span>App Lock<small>PIN</small></span><b>›</b></div><div class="settings-row"><span>Biometric Unlock<small>Fingerprint</small></span><div class="toggle"></div></div><div class="settings-row"><span>Hide Codes<small>Protect codes on screen</small></span><b>○</b></div><div class="settings-row"><span>Encrypted Backup<small>Export accounts securely</small></span><b>›</b></div><button class="primary" onclick="showHome()">Done</button>`)}
function showHome(){overlay.classList.add('hidden');document.querySelector('.bottom-nav .active').classList.add('active')}
function focusSearch(){document.getElementById('search').focus()}
function filterAccounts(){const q=document.getElementById('search').value.toLowerCase();document.querySelectorAll('.account').forEach(a=>a.style.display=a.dataset.name.toLowerCase().includes(q)?'flex':'none')}
