(() => {
  let stream=null,raf=0,detector=null,scanning=false;
  const load=async()=>{const r=await fetch(`app/connect/scanner/index.html?v=20260917a`,{cache:'no-store'});if(!r.ok)throw new Error('Scanner could not be loaded.');return r.text();};
  const stop=()=>{scanning=false;if(raf)cancelAnimationFrame(raf);raf=0;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;detector=null;};
  const handle=raw=>{const value=String(raw||'').trim();if(!value)return;const status=document.getElementById('connectFeatureScanStatus');if(value.toUpperCase().startsWith('INDOONE_CONNECT:')){const code=value.slice(16).trim();const input=document.getElementById('connectPairingCode');if(input)input.value=code;if(status)status.textContent='Pairing code detected. Tap Connect.';}else if(status)status.textContent='QR detected. This code is not an Indoone pairing code.';};
  async function loop(video){if(!scanning)return;try{if(video.readyState>=2){const codes=await detector.detect(video);const raw=codes?.[0]?.rawValue;if(raw){handle(raw);stop();return;}}}catch(_){}raf=requestAnimationFrame(()=>loop(video));}
  async function camera(){const status=document.getElementById('connectFeatureScanStatus'),video=document.getElementById('connectFeatureScanVideo');if(!navigator.mediaDevices?.getUserMedia){if(status)status.textContent='Camera is not available on this device.';return;}try{if(window.IndooneNative?.requestCameraPermission)window.IndooneNative.requestCameraPermission();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();if('BarcodeDetector' in window){detector=new BarcodeDetector({formats:['qr_code']});scanning=true;loop(video);if(status)status.textContent='Camera ready. Point it at an Indoone QR.';}else if(status)status.textContent='Camera is on, but QR decoding is not supported here.';}catch(error){if(status)status.textContent=error?.name==='NotAllowedError'?'Camera permission denied.':'Unable to open camera.';}}
  async function image(file){if(!file)return;if(!('BarcodeDetector' in window))return window.toast?.('Image QR scanning is not supported here.');try{const img=new Image();img.src=URL.createObjectURL(file);await img.decode();const d=new BarcodeDetector({formats:['qr_code']});const codes=await d.detect(img);handle(codes?.[0]?.rawValue);URL.revokeObjectURL(img.src);}catch(_){window.toast?.('Could not read that QR image.');}}
  window.showConnectScanner=async()=>{stop();try{openModal(await load());const modal=document.getElementById('modal');modal?.querySelectorAll('[data-scanner-close]').forEach(b=>b.addEventListener('click',()=>{stop();window.closeModal?.();}));modal?.querySelector('[data-connect-image]')?.addEventListener('click',()=>modal.querySelector('#connectFeatureImageInput')?.click());modal?.querySelector('#connectFeatureImageInput')?.addEventListener('change',e=>image(e.target.files?.[0]));modal?.querySelector('[data-connect-code]')?.addEventListener('click',()=>{const code=modal.querySelector('#connectPairingCode')?.value.trim();if(!code)return window.toast?.('Enter a pairing code.');window.toast?.('Pairing code ready for nearby connection.');});camera();}catch(error){window.toast?.(error?.message||'Could not open scanner.');}};
})();
