(() => {
  let stream = null;
  let raf = 0;
  let detector = null;
  let scanning = false;

  async function loadMarkup(){const response=await fetch(`app/connect/scanner/index.html?v=20260917a`,{cache:'no-store'});if(!response.ok)throw new Error('Scanner could not be loaded.');return response.text();}
  function stop(){scanning=false;if(raf)cancelAnimationFrame(raf);raf=0;if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;detector=null;}
  function result(raw){const value=String(raw||'').trim();if(!value)return;if(value.toUpperCase().startsWith('INDOONE_CONNECT:')){const code=value.slice('INDOONE_CONNECT:'.length).trim();document.getElementById('connectPairingCode').value=code;document.getElementById('connectFeatureScanStatus').textContent='Pairing code detected. Tap Connect.';return;}window.toast?.('QR detected.');}
  async function loop(video){if(!scanning)return;try{if(video.readyState>=2){const codes=await detector.detect(video);const raw=codes?.[0]?.rawValue;if(raw){result(raw);stop();return;}}}catch(_){ }raf=requestAnimationFrame(()=>loop(video));}
  async function camera(){const status=document.getElementById('connectFeatureScanStatus');const video=document.getElementById('connectFeatureScanVideo');if(!navigator.mediaDevices?.getUserMedia){if(status)status.textContent='Camera is not available on this device.';return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();if('BarcodeDetector' in window){detector=new BarcodeDetector({formats:['qr_code']});scanning=true;loop(video);if(status)status.textContent='Camera ready. Point it at an Indoone QR.';}else if(status)status.textContent='Camera is on, but QR decoding is not supported in this browser.';}catch(error){if(status)status.textContent=error?.name==='NotAllowedError'?'Camera permission denied.':'Unable to open camera.';}}
  async function image(file){if(!file)return;if(!('BarcodeDetector' in window)){window.toast?.('Image QR scanning is not supported here.');return;}try{const image=new Image();image.src=URL.createObjectURL(file);await image.decode();const imageDetector=new BarcodeDetector({formats:['qr_code']});const codes=await imageDetector.detect(image);const raw=codes?.[0]?.rawValue;if(raw)result(raw);else window.toast?.('No QR code found in that image.');URL.revokeObjectURL(image.src);}catch(_){window.toast?.('Could not read that QR image.');}}
  window.showConnectScanner=async function(){stop();try{const markup=await loadMarkup();openModal(markup);const modal=document.getElementById('modal');modal?.querySelectorAll('[data-scanner-close]').forEach(button=>button.addEventListener('click',()=>{stop();window.closeModal?.();}));modal?.querySelector('[data-connect-image]')?.addEventListener('click',()=>modal.querySelector('#connectFeatureImageInput')?.click());modal?.querySelector('#connectFeatureImageInput')?.addEventListener('change',event=>image(event.target.files?.[0]));modal?.querySelector('[data-connect-code]')?.addEventListener('click',()=>{const code=modal.querySelector('#connectPairingCode')?.value.trim();if(!code)return window.toast?.('Enter a pairing code.');window.dispatchEvent(new CustomEvent('indoone-connect-code',{detail:{code}}));modal.querySelector('#connectFeatureScanStatus').textContent='Pairing code received. Nearby connection can be started next.';window.toast?.('Pairing code ready.');});camera();}catch(error){window.toast?.(error?.message||'Could not open scanner.');}};
})();
