(() => {
  let endpoints=new Map();
  const load=async()=>{const r=await fetch(`app/connect/connect-device/index.html?v=20260917a`,{cache:'no-store'});if(!r.ok)throw new Error('Connect flow could not be loaded.');return r.text();};
  const esc=v=>String(v||'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const name=()=>localStorage.getItem('indoone_connect_device_name')||'Indoone Device';
  function render(){const host=document.getElementById('connectFeatureNearbyList');if(!host)return;const rows=[...endpoints].map(([id,item])=>`<div class="device-nearby-row"><div><b>${esc(item.name)}</b><small>Nearby device</small></div><button class="primary" data-nearby-endpoint="${esc(id)}">Connect</button></div>`).join('');host.innerHTML=rows||'<div class="connect-empty">Searching for nearby Indoone devices…</div>';}
  function target(type){const mobile=type==='phone';openModal(`<div class="modal-head"><div><p class="eyebrow">NEARBY DISCOVERY</p><h2>${mobile?'Connect phone':'Connect laptop / PC'}</h2></div><button class="close-btn" data-device-flow-close>×</button></div><p class="connect-muted">Keep both devices nearby and keep Indoone open.</p><div class="device-connect-actions"><button class="primary" data-device-start>${mobile?'Find Nearby Phone':'Find Nearby Computer'}</button><button class="secondary" data-device-show-qr>Show My QR</button></div><div id="connectFeatureNearbyList" class="device-nearby-list"></div><p id="connectFeatureNearbyStatus" class="connect-muted">Ready to search.</p>`);const modal=document.getElementById('modal');modal?.querySelectorAll('[data-device-flow-close]').forEach(b=>b.addEventListener('click',()=>window.closeModal?.()));modal?.querySelector('[data-device-start]')?.addEventListener('click',()=>{const status=modal.querySelector('#connectFeatureNearbyStatus');if(window.IndooneNative){window.IndooneNative.requestNearbyPermissions?.();window.IndooneNative.startNearbyDiscovery?.();if(status)status.textContent='Searching for nearby Indoone devices…';}else if(status)status.textContent='Nearby Connect works in the Android app.';});modal?.querySelector('[data-device-show-qr]')?.addEventListener('click',()=>window.showConnectQr?.());render();}
  window.showConnectChoice=async()=>{try{openModal(await load());const modal=document.getElementById('modal');modal?.querySelectorAll('[data-device-connect-close]').forEach(b=>b.addEventListener('click',()=>window.closeModal?.()));modal?.querySelectorAll('[data-device-target]').forEach(b=>b.addEventListener('click',()=>target(b.dataset.deviceTarget)));}catch(e){window.toast?.(e?.message||'Could not open Connect.');}};
  window.addEventListener('indoone-nearby',e=>{const d=e.detail||{};if(d.type==='endpointFound')endpoints.set(d.endpointId||d.message,{name:d.message||'Nearby Indoone Device'});if(d.type==='endpointLost')endpoints.delete(d.endpointId||d.message);render();const id=d.type==='connectionResult'&&d.message==='connected'?d.endpointId:'';if(id&&endpoints.has(id))window.toast?.(`${endpoints.get(id).name} connected.`);});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-nearby-endpoint]');if(!b)return;e.preventDefault();const id=b.dataset.nearbyEndpoint;if(window.IndooneNative?.connectNearbyEndpoint)window.IndooneNative.connectNearbyEndpoint(id,name());else window.toast?.('Nearby Connect works in the Android app.');});
})();
